/**
 * RoadReady — M-Pesa B2C (Business to Customer)
 *
 * Used to pay providers from the RoadReady platform account to their M-Pesa.
 * This is the reverse of the STK Push (which collects from customers).
 *
 * B2C requires:
 *   - A Safaricom Business M-Pesa account (not a personal account)
 *   - Approval from Safaricom for the B2C product (takes 2-4 weeks)
 *   - A security certificate (self-signed or Safaricom-issued)
 *   - Initiator name and password configured in the Safaricom portal
 *
 * Additional env vars needed:
 *   MPESA_B2C_INITIATOR_NAME     — your initiator name from Safaricom portal
 *   MPESA_B2C_SECURITY_CREDENTIAL — base64-encoded encrypted password
 *   MPESA_B2C_RESULT_URL         — public HTTPS URL for result callback
 *   MPESA_B2C_QUEUE_TIMEOUT_URL  — public HTTPS URL for timeout callback
 *
 * The security credential is generated by encrypting your initiator password
 * with Safaricom's public certificate:
 *   openssl rsautl -encrypt -pubin -inkey safaricom.pub -in password.txt | base64
 *
 * Docs: https://developer.safaricom.co.ke/APIs/BusinessToCustomer
 */

const MPESA_BASE = process.env.MPESA_ENV === 'production'
  ? 'https://api.safaricom.co.ke'
  : 'https://sandbox.safaricom.co.ke';

const SHORTCODE          = process.env.MPESA_SHORTCODE    || '174379';
const CONSUMER_KEY       = process.env.MPESA_CONSUMER_KEY;
const CONSUMER_SECRET    = process.env.MPESA_CONSUMER_SECRET;
const INITIATOR_NAME     = process.env.MPESA_B2C_INITIATOR_NAME     || 'testapi';
const SECURITY_CREDENTIAL= process.env.MPESA_B2C_SECURITY_CREDENTIAL|| 'Safaricom999!';
const RESULT_URL         = process.env.MPESA_B2C_RESULT_URL;
const QUEUE_TIMEOUT_URL  = process.env.MPESA_B2C_QUEUE_TIMEOUT_URL;

// Re-use the access token helper from mpesa.js
const { getAccessToken: _getToken } = (() => {
  let cached = null, exp = 0;
  return {
    getAccessToken: async () => {
      if (cached && Date.now() < exp - 60000) return cached;
      const creds = Buffer.from(`${CONSUMER_KEY}:${CONSUMER_SECRET}`).toString('base64');
      const res   = await fetch(`${MPESA_BASE}/oauth/v1/generate?grant_type=client_credentials`, {
        headers: { Authorization: `Basic ${creds}` },
      });
      const data = await res.json();
      cached = data.access_token;
      exp    = Date.now() + parseInt(data.expires_in) * 1000;
      return cached;
    }
  };
})();

function normalisePhone(phone) {
  const d = phone.replace(/\D/g,'');
  if (d.startsWith('254') && d.length === 12) return d;
  if (d.startsWith('07') && d.length === 10)  return '254' + d.slice(1);
  if (d.startsWith('01') && d.length === 10)  return '254' + d.slice(1);
  return d;
}

// ─── Initiate B2C Payment ─────────────────────────────────────────────────────

async function initiateB2CPayout({ phone, amount, payoutId, occasion }) {
  if (!RESULT_URL || !QUEUE_TIMEOUT_URL) {
    throw new Error('MPESA_B2C_RESULT_URL and MPESA_B2C_QUEUE_TIMEOUT_URL are required');
  }

  const token     = await _getToken();
  const normPhone = normalisePhone(phone);

  const body = {
    InitiatorName:      INITIATOR_NAME,
    SecurityCredential: SECURITY_CREDENTIAL,
    CommandID:          'BusinessPayment',   // direct payment to M-Pesa wallet
    Amount:             Math.floor(amount),  // integer KES only
    PartyA:             SHORTCODE,
    PartyB:             normPhone,
    Remarks:            `RoadReady payout ${payoutId}`,
    QueueTimeOutURL:    QUEUE_TIMEOUT_URL,
    ResultURL:          RESULT_URL,
    Occasion:           occasion || payoutId,
  };

  const res  = await fetch(`${MPESA_BASE}/mpesa/b2c/v3/paymentrequest`, {
    method:  'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body:    JSON.stringify(body),
  });
  const data = await res.json();

  if (!res.ok || data.ResponseCode !== '0') {
    throw new Error(`B2C initiation failed: ${data.ResponseDescription || JSON.stringify(data)}`);
  }

  console.log(JSON.stringify({
    level: 'INFO', event: 'b2c_payout_initiated',
    payoutId, phone: normPhone.replace(/(\d{3})\d{4}(\d{3})/, '$1****$2'),
    conversationId: data.ConversationID,
    amount,
  }));

  return {
    conversationId:      data.ConversationID,
    originatorConvId:    data.OriginatorConversationID,
    responseDescription: data.ResponseDescription,
  };
}

// ─── Parse B2C Result Callback ────────────────────────────────────────────────
// Safaricom calls POST /api/payouts/mpesa/result with this body.

function parseB2CResult(body) {
  const result = body?.Result;
  if (!result) return null;

  const params  = result.ResultParameters?.ResultParameter || [];
  const find    = (key) => params.find(p => p.Key === key)?.Value;

  return {
    resultType:      result.ResultType,
    resultCode:      result.ResultCode,
    resultDesc:      result.ResultDesc,
    conversationId:  result.ConversationID,
    success:         result.ResultCode === 0,
    transactionId:   find('TransactionID'),
    amount:          find('TransactionAmount'),
    receiverName:    find('ReceiverPartyPublicName'),
    completedTime:   find('TransactionCompletedDateTime'),
    b2cCharges:      find('B2CChargesPaidAccountAvailableFunds'),
    utilityBalance:  find('B2CUtilityAccountAvailableFunds'),
  };
}

// ─── Is B2C configured? ────────────────────────────────────────────────────────

function isB2CConfigured() {
  return !!(CONSUMER_KEY && CONSUMER_SECRET && RESULT_URL && QUEUE_TIMEOUT_URL &&
            INITIATOR_NAME && SECURITY_CREDENTIAL);
}

module.exports = { initiateB2CPayout, parseB2CResult, isB2CConfigured };
